spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      path: /h2-console
      enabled: true